In [1]:
print("yo")

yo

In [2]:
!pip list

Package                   Version
------------------------- --------------
altgraph                  0.17.4
anyio                     4.4.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     23.2.0
Babel                     2.15.0
beautifulsoup4            4.12.3
bleach                    6.1.0
certifi                   2024.2.2
cffi                      1.16.0
charset-normalizer        3.3.2
colorama                  0.4.6
comm                      0.2.2
contourpy                 1.3.1
cycler                    0.12.1
debugpy                   1.8.2
decorator                 5.1.1
defusedxml                0.7.1
executing                 2.0.1
fastjsonschema            2.20.0
fonttools                 4.56.0
fqdn                      1.5.1
h11                       0.14.0
httpcore                  1.0.5
httpx                     0.27.0
idna                      3.7
ipykernel                 6.29.5
ipython                   8.26.0
ipywidgets                8.1.3
isoduration               20.11.0
jedi                      0.19.1
Jinja2                    3.1.4
json5                     0.9.25
jsonpointer               3.0.0
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
jupyter                   1.0.0
jupyter_client            8.6.2
jupyter-console           6.6.3
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter_server            2.14.1
jupyter_server_terminals  0.5.3
jupyterlab                4.2.3
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.2
jupyterlab_widgets        3.0.11
kiwisolver                1.4.8
MarkupSafe                2.1.5
matplotlib                3.10.0
matplotlib-inline         0.1.7
mistune                   3.0.2
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nest-asyncio              1.6.0
notebook                  7.2.1
notebook_shim             0.2.4
numpy                     2.2.1
overrides                 7.7.0
packaging                 24.1
pandas                    2.3.3
pandocfilters             1.5.1
parso                     0.8.4
pefile                    2023.2.7
pillow                    11.1.0
pip                       25.0
platformdirs              4.2.2
prometheus_client         0.20.0
prompt_toolkit            3.0.47
psutil                    6.0.0
pure-eval                 0.2.2
pycparser                 2.22
Pygments                  2.18.0
pyinstaller               6.12.0
pyinstaller-hooks-contrib 2025.1
pyparsing                 3.2.1
python-dateutil           2.9.0.post0
python-json-logger        2.0.7
pytz                      2025.2
pywin32                   306
pywin32-ctypes            0.2.3
pywinpty                  2.0.13
PyYAML                    6.0.1
pyzmq                     26.2.0
qtconsole                 5.5.2
QtPy                      2.4.1
referencing               0.35.1
requests                  2.32.2
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.18.1
scipy                     1.15.2
Send2Trash                1.8.3
setuptools                70.2.0
six                       1.16.0
sniffio                   1.3.1
soupsieve                 2.5
stack-data                0.6.3
terminado                 0.18.1
tinycss2                  1.3.0
tornado                   6.4.1
traitlets                 5.14.3
types-python-dateutil     2.9.0.20240316
tzdata                    2025.2
uri-template              1.3.0
urllib3                   2.2.1
uv                        0.7.16
wcwidth                   0.2.13
webcolors                 24.6.0
webencodings              0.5.1
websocket-client          1.8.0
wheel                     0.43.0
widgetsnbextension        4.0.11

In [4]:
import pandas as pd

df = pd.read_csv("complete.csv")

print(df)

     awardYear           category  \
0         2001  Economic Sciences
1         1975            Physics
2         2004          Chemistry
3         1982          Chemistry
4         1979            Physics
..         ...                ...
945       1972            Physics
946       1954          Chemistry
947       1911          Chemistry
948       1981              Peace
949       1963              Peace

                                      categoryFullName  sortOrder portion  \
0    The Sveriges Riksbank Prize in Economic Scienc...          2     1/3
1                           The Nobel Prize in Physics          1     1/3
2                         The Nobel Prize in Chemistry          1     1/3
3                         The Nobel Prize in Chemistry          1       1
4                           The Nobel Prize in Physics          2     1/3
..                                                 ...        ...     ...
945                         The Nobel Prize in Physics          1     1/3
946                       The Nobel Prize in Chemistry          1       1
947                       The Nobel Prize in Chemistry          1       1
948                              The Nobel Peace Prize          1       1
949                              The Nobel Peace Prize          1     1/2

     prizeAmount  prizeAmountAdjusted dateAwarded prizeStatus  \
0       10000000             12295082  2001-10-10    received
1         630000              3404179  1975-10-17    received
2       10000000             11762861  2004-10-06    received
3        1150000              3102518  1982-10-18    received
4         800000              2988048  1979-10-15    received
..           ...                  ...         ...         ...
945       480000              3345725         NaN    received
946       181647              2640218         NaN    received
947       140695              7327865         NaN    received
948      1000000              2929688  1981-10-14    received
949       265000              2839286  1963-10-10    received

                                            motivation  ...  \
0    for their analyses of markets with asymmetric ...  ...
1    for the discovery of the connection between co...  ...
2    for the discovery of ubiquitin-mediated protei...  ...
3    for his development of crystallographic electr...  ...
4    for their contributions to the theory of the u...  ...
..                                                 ...  ...
945  for their jointly developed theory of supercon...  ...
946  for his research into the nature of the chemic...  ...
947  in recognition of her services to the advancem...  ...
948   for promoting the fundamental rights of refugees  ...
949  for promoting the principles of the Geneva Con...  ...

    org_founded_country org_founded_countryNow  org_founded_locationString  \
0                   NaN                    NaN                         NaN
1                   NaN                    NaN                         NaN
2                   NaN                    NaN                         NaN
3                   NaN                    NaN                         NaN
4                   NaN                    NaN                         NaN
..                  ...                    ...                         ...
945                 NaN                    NaN                         NaN
946                 NaN                    NaN                         NaN
947                 NaN                    NaN                         NaN
948         Switzerland            Switzerland         Geneva, Switzerland
949         Switzerland            Switzerland         Geneva, Switzerland

       ind_or_org residence_1 residence_2  \
0      Individual         NaN         NaN
1      Individual         NaN         NaN
2      Individual         NaN         NaN
3      Individual         NaN         NaN
4      Individual         NaN         NaN
..            ...         ...         ...
945    Individual         NaN         NaN
946    Individual         NaN         NaN
947    Individual         NaN         NaN
948  Organization         NaN         NaN
949  Organization         NaN         NaN

                                         affiliation_1  \
0               Stanford University, Stanford, CA, USA
1            Niels Bohr Institute, Copenhagen, Denmark
2    Technion - Israel Institute of Technology, Hai...
3    MRC Laboratory of Molecular Biology, Cambridge...
4    International Centre for Theoretical Physics, ...
..                                                 ...
945            University of Illinois, Urbana, IL, USA
946  California Institute of Technology (Caltech), ...
947                 Sorbonne University, Paris, France
948                                                NaN
949                                                NaN

                                affiliation_2 affiliation_3 affiliation_4
0                                         NaN           NaN           NaN
1                                         NaN           NaN           NaN
2                                         NaN           NaN           NaN
3                                         NaN           NaN           NaN
4    Imperial College, London, United Kingdom           NaN           NaN
..                                        ...           ...           ...
945                                       NaN           NaN           NaN
946                                       NaN           NaN           NaN
947                                       NaN           NaN           NaN
948                                       NaN           NaN           NaN
949                                       NaN           NaN           NaN

[950 rows x 52 columns]

In [6]:
lit = df[df["category"] == "Literature"]

In [8]:
lit.sort_values(by='awardYear')

,awardYear,category,categoryFullName,sortOrder,portion,prizeAmount,prizeAmountAdjusted,dateAwarded,prizeStatus,motivation,...,org_founded_country,org_founded_countryNow,org_founded_locationString,ind_or_org,residence_1,residence_2,affiliation_1,affiliation_2,affiliation_3,affiliation_4
836,1901,Literature,The Nobel Prize in Literature,1,1,150782,8567159,NaN,received,in special recognition of his poetic compositi...,...,NaN,NaN,NaN,Individual,France,NaN,NaN,NaN,NaN,NaN
850,1902,Literature,The Nobel Prize in Literature,1,1,141847,8059489,NaN,received,the greatest living master of the art of histo...,...,NaN,NaN,NaN,Individual,Germany,NaN,NaN,NaN,NaN,NaN
100,1903,Literature,The Nobel Prize in Literature,1,1,141358,7795478,NaN,received,"as a tribute to his noble, magnificent and ver...",...,NaN,NaN,NaN,Individual,Norway,NaN,NaN,NaN,NaN,NaN
259,1904,Literature,The Nobel Prize in Literature,1,1/2,140859,7767960,NaN,received,in recognition of the fresh originality and tr...,...,NaN,NaN,NaN,Individual,France,NaN,NaN,NaN,NaN,NaN
480,1904,Literature,The Nobel Prize in Literature,2,1/2,140859,7767960,NaN,received,in recognition of the numerous and brilliant c...,...,NaN,NaN,NaN,Individual,Spain,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
840,2015,Literature,The Nobel Prize in Literature,1,1,8000000,8384572,2015-10-08,received,"for her polyphonic writings, a monument to suf...",...,NaN,NaN,NaN,Individual,Belarus,NaN,NaN,NaN,NaN,NaN
101,2016,Literature,The Nobel Prize in Literature,1,1,8000000,8301051,2016-10-13,received,for having created new poetic expressions with...,...,NaN,NaN,NaN,Individual,NaN,NaN,NaN,NaN,NaN,NaN
506,2017,Literature,The Nobel Prize in Literature,1,1,9000000,9176183,2017-10-05,received,"who, in novels of great emotional force, has u...",...,NaN,NaN,NaN,Individual,NaN,NaN,NaN,NaN,NaN,NaN
635,2018,Literature,The Nobel Prize in Literature,1,1,9000000,9000000,2019-10-10,received,for a narrative imagination that with encyclop...,...,NaN,NaN,NaN,Individual,"Wroclaw, Poland",NaN,NaN,NaN,NaN,NaN
683,2019,Literature,The Nobel Prize in Literature,1,1,9000000,9000000,2019-10-10,received,for an influential work that with linguistic i...,...,NaN,NaN,NaN,Individual,"Chaville, France",NaN,NaN,NaN,NaN,NaN

In [10]:
lit.loc[683]

awardYear                                                                  2019
category                                                             Literature
categoryFullName                                 The Nobel Prize in  Literature
sortOrder                                                                     1
portion                                                                       1
prizeAmount                                                             9000000
prizeAmountAdjusted                                                     9000000
dateAwarded                                                          2019-10-10
prizeStatus                                                            received
motivation                    for an influential work that with linguistic i...
categoryTopMotivation                                                       NaN
award_link                    https://masterdataapi.nobelprize.org/2/nobelPr...
id                                                                          980
name                                                               Peter Handke
knownName                                                          Peter Handke
givenName                                                                 Peter
familyName                                                               Handke
fullName                                                           Peter Handke
penName                                                                     NaN
gender                                                                     male
laureate_link                 http://masterdataapi.nobelprize.org/2/laureate...
birth_date                                                           1942-12-06
birth_city                                                              Griffen
birth_cityNow                                                           Griffen
birth_continent                                                          Europe
birth_country                                                           Austria
birth_countryNow                                                        Austria
birth_locationString                                           Griffen, Austria
death_date                                                                  NaN
death_city                                                                  NaN
death_cityNow                                                               NaN
death_continent                                                             NaN
death_country                                                               NaN
death_countryNow                                                            NaN
death_locationString                                                        NaN
orgName                                                                     NaN
nativeName                                                                  NaN
acronym                                                                     NaN
org_founded_date                                                            NaN
org_founded_city                                                            NaN
org_founded_cityNow                                                         NaN
org_founded_continent                                                       NaN
org_founded_country                                                         NaN
org_founded_countryNow                                                      NaN
org_founded_locationString                                                  NaN
ind_or_org                                                           Individual
residence_1                                                    Chaville, France
residence_2                                                                 NaN
affiliation_1                                                               NaN
affiliation_2                                                               NaN
affiliation_3                                                               NaN
affiliation_4                                                               NaN
Name: 683, dtype: object

In [11]:
lit.loc[683]["motivation"]

'for an influential work that with linguistic ingenuity has explored the periphery and the specificity of human experience'

In [12]:
!pip install wikipedia

Defaulting to user installation because normal site-packages is not writeable
Collecting wikipedia
  Downloading wikipedia-1.4.0.tar.gz (27 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: beautifulsoup4 in c:\users\mahir daiyan\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from wikipedia) (4.12.3)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in c:\users\mahir daiyan\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from wikipedia) (2.32.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mahir daiyan\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mahir daiyan\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mahir daiyan\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mahir daiyan\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2024.2.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\mahir daiyan\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from beautifulsoup4->wikipedia) (2.5)
Building wheels for collected packages: wikipedia
  Building wheel for wikipedia (setup.py): started
  Building wheel for wikipedia (setup.py): finished with status 'done'
  Created wheel for wikipedia: filename=wikipedia-1.4.0-py3-none-any.whl size=11705 sha256=dbda747ff917cad4f174b761159c2c4e17873e1f9d40466d5e230b16a0c12718
  Stored in directory: c:\users\mahir daiyan\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local\pip\cache\wheels\63\47\7c\a9688349aa74d228ce0a9023229c6c0ac52ca2a40fe87679b8
Successfully built wikipedia
Installing collected packages: wikipedia
Successfully installed wikipedia-1.4.0

[notice] A new release of pip is available: 25.0 -> 26.0.1
[notice] To update, run: C:\Users\Mahir Daiyan\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [14]:
import wikipedia

url = "https://en.wikipedia.org/wiki/Han_Kang"

# Split by the standard Wikipedia path and take the last part
title = url.split("/wiki/")[-1]

# # Replace underscores with spaces (optional but cleaner)
# title = title.replace("_", " ")

# Fetch the exact page
page = wikipedia.page(title)
print("Title Found:", page.title)
print("Summary preview:", page.summary[:100], "...")

PageError: Page id "han lang" does not match any pages. Try another id!

In [15]:
title

'Han_Kang'

In [ ]:
page = wikipedia.page("han kang")

In [21]:
page.__dir__()

['title',
 'original_title',
 'pageid',
 'url',
 '__module__',
 '__doc__',
 '__init__',
 '__repr__',
 '__eq__',
 '_WikipediaPage__load',
 '_WikipediaPage__continued_query',
 '_WikipediaPage__title_query_param',
 'html',
 'content',
 'revision_id',
 'parent_id',
 'summary',
 'images',
 'coordinates',
 'references',
 'links',
 'categories',
 'sections',
 'section',
 '__dict__',
 '__weakref__',
 '__hash__',
 '__new__',
 '__str__',
 '__getattribute__',
 '__setattr__',
 '__delattr__',
 '__lt__',
 '__le__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__reduce_ex__',
 '__reduce__',
 '__getstate__',
 '__subclasshook__',
 '__init_subclass__',
 '__format__',
 '__sizeof__',
 '__dir__',
 '__class__']

In [22]:
page.content

'The Nobel Prize in Literature, here meaning for Literature (Swedish: Nobelpriset i litteratur), is a Swedish literature prize that is awarded annually to an author from any country who has, in the words of Alfred Nobel, "in the field of literature, produced the most outstanding work in an idealistic direction". Though individual works are sometimes cited as being particularly noteworthy, the award is based on an author\'s body of work as a whole. The Swedish Academy decides who, if anyone, will receive the prize.\nThe academy announces the name of the laureate in early October. It is one of the five Nobel Prizes established by the will of Alfred Nobel in 1895. Literature is traditionally the final award presented at the Nobel Prize ceremony. On some occasions, the award has been postponed to the following year, most recently in 2018.\n\n\n== Background ==\n\nAlfred Nobel stipulated in his last will and testament that his money be used to create a series of prizes for those who confer the "greatest benefit on mankind" in physics, chemistry, peace, physiology or medicine, and literature. Although Nobel wrote several wills during his lifetime, the last was written a little over a year before he died, and it was signed at the Swedish-Norwegian Club in Paris on 27 November 1895. Nobel bequeathed 94% of his total assets, 31 million Swedish kronor (US$198 million, €176 million in 2016), to establish and endow the five Nobel Prizes. Due to the level of scepticism surrounding the will, it was not until 26 April 1897 that the Storting (Norwegian Parliament) approved it. The executors of his will were Ragnar Sohlman and Rudolf Lilljequist, who formed the Nobel Foundation to take care of Nobel\'s fortune and organise the prizes.\nThe members of the Norwegian Nobel Committee that were to award the Peace Prize were appointed shortly after the will was approved. The prize-awarding organisations followed: the Karolinska Institutet on 7 June, the Swedish Academy on 9 June, and the Royal Swedish Academy of Sciences on 11 June. The Nobel Foundation then reached an agreement on guidelines for how the Nobel Prize should be awarded. In 1900, the Nobel Foundation\'s newly created statutes were promulgated by King Oscar II. According to Nobel\'s will, the prize in literature should be determined by "the Academy in Stockholm", which was specified by the statutes of the Nobel Foundation to mean the Swedish Academy.\n\n\n== Nomination and award procedure ==\n\nEach year, the Swedish Academy sends out requests for nominations of candidates for the Nobel Prize in Literature. Members of the Academy, members of literature academies and societies, professors of literature and language, former Nobel literature laureates, and the presidents of writers\' organisations are all allowed to nominate a candidate. One cannot nominate oneself.\nBetween 1901 and 1950, around 20 to 35 nominations were usually received each year. Since then, thousands of requests are sent out each year, and as of 2011 about 220 proposals were returned. These proposals must be received by the Academy by 1 February, after which they are examined by the Nobel Committee, a working group within the Academy comprising four to five members. By April, the committee narrows the field to around 20 candidates. By May, a shortlist of five names is approved by the Academy. The next four months are spent reading and reviewing the works of the five candidates. In October, members of the Academy vote, and the candidate who receives more than half of the votes is named the Nobel laureate in Literature. No one can get the prize without being on the shortlist at least twice; thus, many authors reappear and are reviewed repeatedly over the years. The academicians read works in their original language, but when a candidate is shortlisted from a language that no member masters, they call on translators and oath-sworn experts to provide samples of that writer\'s work. Other elements of the process are similar to those of other Nobel Prizes. The Swedish Academy is composed of 18 members who are elected for life and, until 2018, not technically permitted to leave. On 2 May 2018, King Carl XVI Gustaf amended the rules of the academy and made it possible for members to resign. The new rules also mention that a member who has been inactive in the work of the academy for more than two years can be asked to resign. The members of the Nobel committee are elected for a period of three years from among the members of the academy and are assisted by specially appointed expert advisers.\nThe award is usually announced in October. Sometimes, however, the award has been announced the year after the nominal year, the latest such case being the 2018 award. In the midst of controversy surrounding claims of sexual assault, conflict of interest, and resignations by officials, on 4 May 2018, the Swedish Academy announced that the 2018 laureate would be announced in 2019 along with the 2019 laureate. Some years, such as in 1949, no candidate received the required majority of the votes, and for that reason, the prize was postponed and announced the following year.\n\n\n=== Withdrawn, invalidated and unarchived nominations ===\nBetween 1901 to 1970, literary historians and archivists noted that there were official nominees who were either withdrawn, invalidated or not archived in the Academy\'s nomination database. In 1911, the Swedish playwright August Strindberg was nominated for the first time by Academy member Nathan Söderblom but because the nomination "arrived too late", it was withdrawn and unarchived unlike any other nominations that were moved to the succeeding year. In 1904, José Echegaray\'s nomination letter "arrived late due to slow mail service" and Rudyard Kipling\'s had been temporarily misplaced. It was then decided by the Nobel committee to include both the nominations for 1904 and not moved for 1905.\nThere have been nine recorded occasions when the nominations were declared invalid. The only nominations for Pedro Pablo Figueroa, Max Haushofer Jr., William Booth and Armando Alvares Pedroso were declared invalid by the Nobel committee because their respective nominators were found to be ineligible. Such declarations also occurred to Ernest Lavisse in 1911, Henriette Charasson in 1945, Teixeira de Pascoaes in 1945 and Enrique Larreta in 1945. Therefore, their names were withdrawn from the archives in those specific years. John Macmillan Brown\'s self-nomination under the pseudonym "Godfrey Sweven" was declared invalid due to the rule that nominations of oneself is impermissible.\nPermanent Secretary of the Swedish Academy Anders Österling revealed to the New York Times days before the announcement that Willa Cather, together with Ernest Hemingway, John Steinbeck, and Gabriela Mistral, was among the contenders for the 1944 prize. Despite the revelation, Cather\'s name was not included in the archives. The prize was eventually given to Johannes V. Jensen.\n\n\n== Prizes ==\n\nA Literature Nobel Prize laureate receives a gold medal, a diploma bearing a citation, and a sum of money. The amount of money awarded depends on the income of the Nobel Foundation that year. The literature prize can be shared between two, but not three, laureates. If a prize is awarded jointly, the prize money is split equally between them.\nThe prize money of the Nobel Prize has been fluctuating since its inauguration but as of 2012 it stood at kr 8,000,000 (about US$1,100,000), previously it was kr 10,000,000. This was not the first time the prize amount was decreased—beginning with a nominal value of kr 150,782 in 1901 (worth 8,123,951 in 2011 SKr) the nominal value has been as low as kr 121,333 (2,370,660 in 2011 SKr) in 1945—but it has been uphill or stable since then, peaking at an SKr-2011 value of 11,659,016 in 2001.\nThe laureate is also invited to give a lecture during "Nobel Week" in Stockholm; the highlight is the prize-giving ceremony and banquet on 10 December. It is the third richest literary prize in the world.\n\n\n=== Medals ===\n\nThe literature medal features a portrait of Alfred Nobel in left profile on the obverse. It was designed by Erik Lindberg. The reverse of the medal depicts a \'young man sitting under a laurel tree who, enchanted, listens to and writes down the song of the Muse\'. It is inscribed "Inventas vitam iuvat excoluisse per artes" ("It is beneficial to have improved (human) life through discovered arts"), an adaptation of "inventas aut qui vitam excoluere per artes" from line 663 of book 6 of the Aeneid by the Roman poet Virgil. A plate below the figures is inscribed with the name of the recipient. The text "ACAD. SUEC." denoting the Swedish Academy is also inscribed on the reverse.\nBetween 1902 and 2010, the Nobel Prize medals were struck by the Myntverket, the Swedish royal mint, located in Eskilstuna. In 2011, the medals were made by the Det Norske Myntverket in Kongsberg. The medals have been made by Svenska Medalj in Eskilstuna since 2012.\n\n\n=== Diplomas ===\nNobel laureates receive a diploma directly from the King of Sweden. Each diploma is uniquely designed by the prize-awarding institutions for the laureate who receives it. The diploma contains a picture and text that states the name of the laureate and normally a citation of why they received the prize.\n\n\n== Laureates ==\n\nThe Nobel Prize in Literature has been awarded 116 times between 1901 and 2024 to 121 individuals: 103 men and 18 women. The prize has been shared between two individuals on four occasions. It was not awarded on seven occasions. The laureates have included writers in 25 languages. The youngest laureate was Rudyard Kipling, who was 41 years old when he was awarded in 1907. The oldest laureate to receive the prize was Doris Lessing, who was 88 when she was awarded in 2007. It has been awarded posthumously once, to Erik Axel Karlfeldt in 1931. On some occasions, the awarding institution, the Swedish Academy, has awarded the prize to its own members; Verner von Heidenstam in 1916, the posthumous prize to Karlfeldt in 1931, Pär Lagerkvist in 1951, and the shared prize to Eyvind Johnson and Harry Martinson in 1974. Selma Lagerlöf was elected a member of the Swedish Academy in 1914, five years after she was awarded the Nobel Prize in 1909. Three writers have declined the prize, Erik Axel Karlfeldt in 1919, Boris Pasternak in 1958 ("Accepted first, later caused by the authorities of his country (Soviet Union) to decline the Prize", according to the Nobel Foundation) and Jean-Paul Sartre in 1964.\n\n\n=== Interpretations of Nobel\'s guidelines ===\nAlfred Nobel\'s guidelines for the prize, stating that the candidate should have bestowed "the greatest benefit on mankind" and written "in an idealistic direction," have sparked much discussion. In the early history of the prize, Nobel\'s "idealism" was read as "a lofty and sound idealism." The set of criteria, characterised by its conservative idealism, holding church, state, and family sacred, resulted in prizes for Bjørnstjerne Bjørnson, Rudyard Kipling, and Paul Heyse. During World War I, there was a policy of neutrality, which partly explains the number of awards to Scandinavian writers. In the 1920s, "idealistic direction" was interpreted more generously as "wide-hearted humanity," leading to awards for writers like Anatole France, George Bernard Shaw, and Thomas Mann. In the 1930s, "the greatest benefit on mankind" was interpreted as writers within every person\'s reach, with authors like Sinclair Lewis and Pearl Buck receiving recognition. In 1946, a renewed Academy changed focus and began to award literary pioneers like Hermann Hesse, André Gide, T. S. Eliot, and William Faulkner. During this era, "the greatest benefit on mankind" was interpreted in a more exclusive and generous way than before. Since the 1970s, the Academy has often given attention to important but internationally unnoticed writers, awarding writers like Elias Canetti and Jaroslav Seifert.\n\nBeginning in 1986, the Academy acknowledged the international aspect in Nobel\'s will, which rejected any consideration of the nationality of the candidates, and awarded authors from all over the world, such as Wole Soyinka from Nigeria, Naguib Mahfouz from Egypt, Octavio Paz from Mexico, Nadine Gordimer from South Africa, Derek Walcott from St. Lucia, Toni Morrison, the first African-American on the list, Kenzaburo Oe from Japan, and Gao Xingjian, the first laureate to write in Chinese. In the 2000s, V. S. Naipaul, Mario Vargas Llosa, and the Chinese writer Mo Yan have been awarded, but the policy of "a prize for the whole world" has been less noticeable as the Academy has mostly continued to award European and English-language writers from the Western literary tradition. In 2015, a rare prize to a non-fiction writer was awarded to Svetlana Alexievich.\n\n\n=== Shared prize ===\n\nThe Nobel Prize in Literature can be shared between two individuals. However, the Academy has been reluctant to award shared prizes, because divisions are liable to be interpreted as a result of a compromise. The shared prizes awarded to Frédéric Mistral and José Echegaray in 1904 and to Karl Gjellerup and Henrik Pontoppidan in 1917 were, in fact, both results of compromises. Shared prizes are exceptional, and more recently, the Academy has awarded a shared prize on only two occasions, to Shmuel Yosef Agnon and Nelly Sachs in 1966, and to Eyvind Johnson and Harry Martinson in 1974.\n\n\n=== Recognition of a specific work ===\n\nNobel Prize Laureates in Literature are awarded for the author\'s life work, but on some occasions, the Academy has singled out a specific work for particular recognition. For example, Knut Hamsun was awarded in 1920 "for his monumental work, Growth of the Soil"; Thomas Mann in 1929 "principally for his great novel, Buddenbrooks, which has won steadily increased recognition as one of the classic works of contemporary literature"; John Galsworthy in 1932 "for his distinguished art of narration which takes its highest form in The Forsyte Saga"; Roger Martin du Gard in 1937 "for the artistic power and truth with which he has depicted human conflict as well as some fundamental aspects of contemporary life in his novel-cycle Les Thibault"; Ernest Hemingway in 1954 "for his mastery of the art of narrative, most recently demonstrated in The Old Man and the Sea; and for the influence that he has exerted on contemporary style"; and Mikhail Sholokhov in 1965 "for the artistic power and integrity with which, in his epic of the Don, he has given expression to a historic phase in the life of the Russian people".\n\n\n=== Potential candidates ===\nNominations are kept secret for at least 50 years before they are publicly available at The Nomination Database for the Nobel Prize in Literature. As of 2025, only nominations submitted between 1901 and 1973 are available for public viewing.\n\nWhat about the rumours circling around the world about certain people being nominated for the Nobel Prize this year? – Well, either it\'s just a rumour, or someone among the invited nominators has leaked information. Since the nominations are kept secret for 50 years, you\'ll have to wait until then to find out.\n\n \nNominated candidates are usually considered by the Nobel committee for years, but it has happened on a number of occasions that an author has been instantly awarded after just one nomination. Apart from the first laureate in 1901, Sully Prudhomme, these include Theodor Mommsen in 1902, Rudolf Eucken in 1908, Paul Heyse in 1910, Rabindranath Tagore in 1913, Sinclair Lewis in 1930, Luigi Pirandello in 1934, Pearl Buck in 1938, William Faulkner in 1950 (the prize for 1949) and Bertrand Russell in 1950.\nFormer recipients of the Nobel Prize in Literature are allowed to nominate their candidates for the prize and sometimes their proposals have subsequently been awarded the prize. The 1912 laureate Gerhart Hauptmann nominated Verner von Heidenstam (awarded in 1916) and Thomas Mann (awarded in 1929), the 1915 laureate Romain Rolland proposed Ivan Bunin (awarded in 1933), Thomas Mann nominated Hermann Hesse (awarded in 1946) in 1931, the 1951 laureate Pär Lagerkvist was proposed by both André Gide and Roger Martin du Gard, and the 1960 laureate Saint-John Perse was nominated several times by the 1948 laureate T. S. Eliot.\n\n\n== Media attention ==\n\nFrom the start the Nobel Prize in Literature attracted much media attention. The first prize in 1901 was reported in hundreds of newspapers in different parts of the world. The prizes to Rudyard Kipling in 1907 and Rabindranath Tagore in 1913 helped to establish the prize as a central phenomenon in world literature. After World War II, the prize has earned more intense media attention with dramatic news reports and in-depth comments from around the world, further establishing its central position in the global literary space. Days before the announcement of the year\'s Nobel laureate in Literature, potential winners are widely guessed in the media, and controversial and surprising choices have often caused much media discussion.\n\n\n== Criticism ==\n\nAlthough the Nobel Prize in Literature is widely regarded as the world\'s most prestigious literary prize, the Swedish Academy has attracted significant criticism for its handling of the award. Many authors who have won the prize have fallen into obscurity, while others rejected by the jury remain widely studied and read. In the Wall Street Journal, Joseph Epstein wrote, "You might not know it, but you and I are members of a club whose fellow members include Leo Tolstoy, Henry James, Anton Chekhov, Mark Twain, Henrik Ibsen, Marcel Proust, James Joyce, Jorge Luis Borges and Vladimir Nabokov. The club is the Non-Winners of the Nobel Prize in Literature. All these authentically great writers, still alive when the prize, initiated in 1901, was being awarded, didn\'t win it." Other notable names from the non-western canon who were ignored despite being nominated several times for the prize include Sri Aurobindo and Sarvepalli Radhakrishnan. The prize has "become widely seen as a political one – a peace prize in literary disguise", whose judges are prejudiced against authors with political tastes different from theirs. Tim Parks has expressed skepticism that it is possible for "Swedish professors ... [to] compar[e] a poet from Indonesia, perhaps translated into English with a novelist from Cameroon, perhaps available only in French, and another who writes in Afrikaans but is published in German and Dutch...". As of 2021, 16 of the 118 recipients have been of Scandinavian origin. The Academy has often been alleged to be biased towards European, and in particular Swedish, authors.\nNobel\'s "vague" wording for the criteria for the prize has led to recurrent controversy. In the original Swedish, the word idealisk translates as "ideal." The Nobel Committee\'s interpretation has varied over the years. In recent years, this means a kind of idealism championing human rights on a broad scale.\n\n\n=== Controversies about Nobel laureate selections ===\nFrom 1901 to 1912, the committee, led by the conservative Carl David af Wirsén, assessed the literary quality of a work in relation to its contribution to humanity\'s pursuit of the "ideal." Leo Tolstoy, Henrik Ibsen, Émile Zola, and Mark Twain were rejected in favour of authors who mostly are little read today.\nLater, the prize has often been controversial due to the Swedish Academy\'s Eurocentric choices of laureates, or for political reasons, as seen in the years 1970, 2005, and 2019, and for the Academy awarding its own members, as happened in 1974.\n\n\n=== Nationality-based criticism ===\n\nThe prize\'s focus on European men, and Swedes in particular, has been the subject of criticism, even from Swedish newspapers. The majority of laureates have been European, with Sweden itself receiving more p

In [23]:
!pip install Wikipedia-API

Defaulting to user installation because normal site-packages is not writeable
Collecting Wikipedia-API
  Downloading wikipedia_api-0.14.1-py3-none-any.whl.metadata (43 kB)
Collecting click==8.3.2 (from Wikipedia-API)
  Downloading click-8.3.2-py3-none-any.whl.metadata (2.6 kB)
Collecting httpx==0.28.1 (from Wikipedia-API)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting tenacity==9.1.4 (from Wikipedia-API)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: colorama in c:\users\mahir daiyan\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from click==8.3.2->Wikipedia-API) (0.4.6)
Requirement already satisfied: anyio in c:\users\mahir daiyan\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httpx==0.28.1->Wikipedia-API) (4.4.0)
Requirement already satisfied: certifi in c:\users\mahir daiyan\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httpx==0.28.1->Wikipedia-API) (2024.2.2)
Requirement already satisfied: httpcore==1.* in c:\users\mahir daiyan\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httpx==0.28.1->Wikipedia-API) (1.0.5)
Requirement already satisfied: idna in c:\users\mahir daiyan\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httpx==0.28.1->Wikipedia-API) (3.7)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\mahir daiyan\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from httpcore==1.*->httpx==0.28.1->Wikipedia-API) (0.14.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\mahir daiyan\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from anyio->httpx==0.28.1->Wikipedia-API) (1.3.1)
Downloading wikipedia_api-0.14.1-py3-none-any.whl (129 kB)
Downloading click-8.3.2-py3-none-any.whl (108 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Installing collected packages: tenacity, click, httpx, Wikipedia-API
  Attempting uninstall: httpx
    Found existing installation: httpx 0.27.0
    Uninstalling httpx-0.27.0:
      Successfully uninstalled httpx-0.27.0
Successfully installed Wikipedia-API-0.14.1 click-8.3.2 httpx-0.28.1 tenacity-9.1.4

[notice] A new release of pip is available: 25.0 -> 26.0.1
[notice] To update, run: C:\Users\Mahir Daiyan\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [17]:
import wikipediaapi
wiki_wiki = wikipediaapi.Wikipedia(user_agent='huma 1678', language='en')

# page_py = wiki_wiki.page('Han kang')
search_results = wiki_wiki.search('Han kang')

In [19]:
search_results.pages

{'Han Kang': Han Kang (lang: en, variant: None, id: ??, ns: 0),
 'Sung Kang': Sung Kang (lang: en, variant: None, id: ??, ns: 0),
 'Kang Han-na': Kang Han-na (lang: en, variant: None, id: ??, ns: 0),
 'Deborah Smith (translator)': Deborah Smith (translator) (lang: en, variant: None, id: ??, ns: 0),
 'The Vegetarian': The Vegetarian (lang: en, variant: None, id: ??, ns: 0),
 '2024 Nobel Prize in Literature': 2024 Nobel Prize in Literature (lang: en, variant: None, id: ??, ns: 0),
 'We Do Not Part': We Do Not Part (lang: en, variant: None, id: ??, ns: 0),
 'Fanletter, Please!': Fanletter, Please! (lang: en, variant: None, id: ??, ns: 0),
 'Han Seung-won': Han Seung-won (lang: en, variant: None, id: ??, ns: 0),
 'Han Lue': Han Lue (lang: en, variant: None, id: ??, ns: 0)}

In [29]:
page_py.sections

[]

In [1]:
import pandas as pd

lit_hub = pd.read_csv("literary_hubs.csv")
lit_hub

          city  birth_count  death_count  total_activity
0        Paris            6            8              14
1       London            2            7               9
2       Madrid            2            5               7
3    Stockholm            1            6               7
4       Dublin            3            1               4
..         ...          ...          ...             ...
152      Vevey            0            1               1
153    Vézelay            0            1               1
154     Warsaw            0            1               1
155      Zushi            0            1               1
156    Övralid            0            1               1

[157 rows x 4 columns]

In [2]:
migration = pd.read_csv("migration_analysis.csv")
migration

,id,name,awardYear,origin,destination,is_migrant
0,569,Sully Prudhomme,1901,France,France,False
1,571,Theodor Mommsen,1902,Germany,Germany,False
2,572,Bjørnstjerne Bjørnson,1903,Norway,Norway,False
3,573,Frédéric Mistral,1904,France,France,False
4,574,José Echegaray,1904,Spain,Spain,False
...,...,...,...,...,...,...
111,924,Svetlana Alexievich,2015,Ukraine,Belarus,True
112,937,Bob Dylan,2016,USA,NaN,False
113,947,Kazuo Ishiguro,2017,Japan,NaN,False
114,979,Olga Tokarczuk,2018,Poland,"Wroclaw, Poland",True
115,980,Peter Handke,2019,Austria,"Chaville, France",True

In [1]:
path = r"..\data\wikipedia_lit_laureates.csv"

import pandas as pd

df =  pd.read_csv(path)

useful_df = df.iloc[103:]

In [15]:
links = list(useful_df["tablescraper-selected-row href 2"])

In [16]:
links

['https://en.wikipedia.org/wiki/Gao_Xingjian',
 'https://en.wikipedia.org/wiki/V._S._Naipaul',
 'https://en.wikipedia.org/wiki/Imre_Kert%C3%A9sz',
 'https://en.wikipedia.org/wiki/J._M._Coetzee',
 'https://en.wikipedia.org/wiki/Elfriede_Jelinek',
 'https://en.wikipedia.org/wiki/Harold_Pinter',
 'https://en.wikipedia.org/wiki/Orhan_Pamuk',
 'https://en.wikipedia.org/wiki/Doris_Lessing',
 'https://en.wikipedia.org/wiki/J._M._G._Le_Cl%C3%A9zio',
 'https://en.wikipedia.org/wiki/Herta_M%C3%BCller',
 'https://en.wikipedia.org/wiki/Mario_Vargas_Llosa',
 'https://en.wikipedia.org/wiki/Tomas_Transtr%C3%B6mer',
 'https://en.wikipedia.org/wiki/Mo_Yan',
 'https://en.wikipedia.org/wiki/Alice_Munro',
 'https://en.wikipedia.org/wiki/Patrick_Modiano',
 'https://en.wikipedia.org/wiki/Svetlana_Alexievich',
 'https://en.wikipedia.org/wiki/Bob_Dylan',
 'https://en.wikipedia.org/wiki/Kazuo_Ishiguro',
 'https://en.wikipedia.org/wiki/Olga_Tokarczuk',
 'https://en.wikipedia.org/wiki/Peter_Handke',
 'https://en.wikipedia.org/wiki/Louise_Gl%C3%BCck',
 'https://en.wikipedia.org/wiki/Abdulrazak_Gurnah',
 'https://en.wikipedia.org/wiki/Annie_Ernaux',
 'https://en.wikipedia.org/wiki/Jon_Fosse',
 'https://en.wikipedia.org/wiki/Han_Kang',
 'https://en.wikipedia.org/wiki/L%C3%A1szl%C3%B3_Krasznahorkai']

In [20]:
import wikipedia

In [21]:
result = wikipedia.search("han kang")

In [22]:
result

['Han Kang',
 'Sung Kang',
 'Kang Han-na',
 'Deborah Smith (translator)',
 'The Vegetarian',
 '2024 Nobel Prize in Literature',
 'We Do Not Part',
 'Fanletter, Please!',
 'Han Seung-won',
 'Han Lue']

In [27]:
pages = []
for res in result:
    try:
        page = wikipedia.page(res)
        pages.append(page)
    except:
        print("error in ", res)

error in  Han Kang
error in  Sung Kang
error in  Kang Han-na
error in  Deborah Smith (translator)
error in  The Vegetarian
error in  2024 Nobel Prize in Literature
error in  We Do Not Part
error in  Fanletter, Please!
error in  Han Seung-won
error in  Han Lue

In [24]:
pages

[]

In [33]:
import requests

url = "https://en.wikipedia.org/w/api.php"
params = {
    "action": "query",
    "prop": "pageprops",
    "titles": "Han_Kang",
    "format": "json"
}

headers = {
    "User-Agent": "MyBot/1.0 (https://example.com/contact)"  # template header which bypasses 403
}

response = requests.get(url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()
    print(data)
else:
    print(f"Failed: {response.status_code}")

{'batchcomplete': '', 'query': {'normalized': [{'from': 'Han_Kang', 'to': 'Han Kang'}], 'pages': {'28222070': {'pageid': 28222070, 'ns': 0, 'title': 'Han Kang', 'pageprops': {'defaultsort': 'Han, Kang', 'page_image_free': 'Han_Kang,_2024_Nobel_Prize_Laureate_in_Literature_(cropped).jpg', 'wikibase-shortdesc': 'South Korean writer (born 1970)', 'wikibase_item': 'Q5646626'}}}}}

In [32]:
data

{'batchcomplete': '',
 'query': {'pages': {'-1': {'title': 'J._M._G._Le_Cl%C3%A9zio',
    'invalidreason': 'The requested page title contains invalid characters: "%C3".',
    'invalid': ''}}}}

In [36]:
data["query"]["pages"]

{'28222070': {'pageid': 28222070,
  'ns': 0,
  'title': 'Han Kang',
  'pageprops': {'defaultsort': 'Han, Kang',
   'page_image_free': 'Han_Kang,_2024_Nobel_Prize_Laureate_in_Literature_(cropped).jpg',
   'wikibase-shortdesc': 'South Korean writer (born 1970)',
   'wikibase_item': 'Q5646626'}}}

In [44]:
data = [
    'https://en.wikipedia.org/wiki/Gao_Xingjian',
    'https://en.wikipedia.org/wiki/V._S._Naipaul',
    'https://en.wikipedia.org/wiki/Imre_Kertész',
    'https://en.wikipedia.org/wiki/J._M._Coetzee',
    'https://en.wikipedia.org/wiki/Elfriede_Jelinek',
    'https://en.wikipedia.org/wiki/Harold_Pinter',
    'https://en.wikipedia.org/wiki/Orhan_Pamuk',
    'https://en.wikipedia.org/wiki/Doris_Lessing',
    'https://en.wikipedia.org/wiki/J._M._G._Le_Clézio',
    'https://en.wikipedia.org/wiki/Herta_Müller',
    'https://en.wikipedia.org/wiki/Mario_Vargas_Llosa',
    'https://en.wikipedia.org/wiki/Tomas_Tranströmer',
    'https://en.wikipedia.org/wiki/Mo_Yan',
    'https://en.wikipedia.org/wiki/Alice_Munro',
    'https://en.wikipedia.org/wiki/Patrick_Modiano',
    'https://en.wikipedia.org/wiki/Svetlana_Alexievich',
    'https://en.wikipedia.org/wiki/Bob_Dylan',
    'https://en.wikipedia.org/wiki/Kazuo_Ishiguro',
    'https://en.wikipedia.org/wiki/Olga_Tokarczuk',
    'https://en.wikipedia.org/wiki/Peter_Handke',
    'https://en.wikipedia.org/wiki/Louise_Glück',
    'https://en.wikipedia.org/wiki/Abdulrazak_Gurnah',
    'https://en.wikipedia.org/wiki/Annie_Ernaux',
    'https://en.wikipedia.org/wiki/Jon_Fosse',
    'https://en.wikipedia.org/wiki/Han_Kang',
    'https://en.wikipedia.org/wiki/László_Krasznahorkai'
    ]

In [45]:
import requests

def wikipedia_helper(links: list):
    for link in links:
        title = link.split("/")[-1]
        print(title)
        url = "https://en.wikipedia.org/w/api.php"
        params = {
            "action": "query",
            "prop": "pageprops",
            "titles": title,
            "format": "json"
        }

        headers = {
            "User-Agent": "MyBot/1.0 (https://example.com/contact)"  # template header which bypasses 403
        }

        response = requests.get(url, params=params, headers=headers)

        if response.status_code == 200:
            data = response.json()
        else:
            print(f"Failed: {response.status_code}")

        if '-1' in data["query"]["pages"]:
            print(f"error in {link}")

wikipedia_helper(data)

Gao_Xingjian
V._S._Naipaul
Imre_Kertész
J._M._Coetzee
Elfriede_Jelinek
Harold_Pinter
Orhan_Pamuk
Doris_Lessing
J._M._G._Le_Clézio
Herta_Müller
Mario_Vargas_Llosa
Tomas_Tranströmer
Mo_Yan
Alice_Munro
Patrick_Modiano
Svetlana_Alexievich
Bob_Dylan
Kazuo_Ishiguro
Olga_Tokarczuk
Peter_Handke
Louise_Glück
Abdulrazak_Gurnah
Annie_Ernaux
Jon_Fosse
Han_Kang
László_Krasznahorkai

In [48]:
url = "https://en.wikipedia.org/w/api.php"
params = {
    "action": "query",
    "prop": "pageprops",
    "titles": "Han_Kang",
    "format": "json"
}

headers = {
    "User-Agent": "MyBot/1.0 (https://example.com/contact)"  # template header which bypasses 403
}

response = requests.get(url, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()

In [49]:
data

{'batchcomplete': '',
 'query': {'normalized': [{'from': 'Han_Kang', 'to': 'Han Kang'}],
  'pages': {'28222070': {'pageid': 28222070,
    'ns': 0,
    'title': 'Han Kang',
    'pageprops': {'defaultsort': 'Han, Kang',
     'page_image_free': 'Han_Kang,_2024_Nobel_Prize_Laureate_in_Literature_(cropped).jpg',
     'wikibase-shortdesc': 'South Korean writer (born 1970)',
     'wikibase_item': 'Q5646626'}}}}}

In [51]:
id = 28222070

page = wikipedia.page(pageid=id)

In [54]:
print(page.content)

Han Kang (Korean: 한강; born 27 November 1970) is a South Korean writer. From 2007 to 2018, she taught creative writing at the Seoul Institute of the Arts. Han rose to international prominence for her novel The Vegetarian, which became the first Korean language novel to win the International Booker Prize for fiction in 2016. Han is the first Asian woman and Korean to be a recipient of the Nobel Prize in Literature, receiving the award in 2024 in recognition of her "intense poetic prose that confronts historical traumas and exposes the fragility of human life".


== Early life and education ==
Han Kang was born on 27 November 1970 in Gwangju, South Korea. According to her father, she is named for the Han River (Korean: 한강; RR: Hangang). Her family is noted for its literary background. Her father is novelist Han Seung-won. Her older brother, Han Dong-rim, is also a novelist, while her younger brother, Han Kang-in, is a novelist and cartoonist.
At the age of nine, Han moved to Suyu-ri in Seoul, when her father quit his teaching job to become a full-time writer, four months before the Gwangju Uprising, a pro-democracy movement that ended in the military's massacre of students and civilians. She first learned about the massacre when she was 12, after discovering at home a secretly circulated memorial album of photographs taken by a German journalist, Jürgen Hinzpeter. This discovery deeply influenced her view on humanity and her literary works.
Han's father struggled to make ends meet with his writing career, which negatively impacted his family. Han later described her childhood as "too much for a little child"; however, being surrounded by books gave her comfort. In 1988, she graduated from Poongmoon Girls' High School, now Poongmoon High School, where she had been a class president. In 1993, Han graduated from Yonsei University, where she majored in Korean language and literature. In 1998, she participated in the University of Iowa International Writing Program for three months with support from the Arts Council Korea.


== Career ==
After graduating from Yonsei University, Han briefly worked as a reporter for the monthly Saemteo magazine. Han's literary career began the same year when five of her poems, including "Winter in Seoul", were featured in the Winter 1993 issue of the quarterly Literature and Society. She made her fiction debut the next year, under the name Han Kang-hyun, when her short story "The Scarlet Anchor" won the New Year's Literary Contest held by the Seoul Shinmun. Her first short story collection, A Love of Yeosu, was published in 1995 and attracted attention for its precise and tightly narrated structure. After the publication, she quit her magazine job to solely focus on writing literature.
In 2007, Han published a book, A Song to Sing Calmly (가만가만 부르는 노래), that was accompanied by a music album. At first she did not intend to sing, but Han Jeong-rim, a musician and music director, insisted that Han Kang record the songs herself. The same year, she started working as a professor in the Department of Creative Writing at the Seoul Institute of the Arts until 2018.
In her college years Han became obsessed with a line of poetry by the Korean modernist poet Yi Sang: "I believe that humans should be plants." She understood Yi's line to imply a defensive stance against the violence of Korea's colonial history under Japanese occupation and took it as an inspiration to write her most successful work, The Vegetarian. The second part of the three-part novel, Mongolian Mark, won the Yi Sang Literary Award. The rest of the series (The Vegetarian and Fire Tree) was delayed by contractual problems.
The Vegetarian was Han's first novel translated into English, although she had already attracted worldwide attention by the time Deborah Smith translated it. The translated work won the International Booker Prize 2016 for both Han and Smith. Han was the first Korean writer to be nominated for the award, and The Vegetarian was the first Korean language novel to win the International Booker Prize for fiction. The Vegetarian was also chosen as one of "The 10 Best Books of 2016" by The New York Times Book Review.

Han's novel Human Acts was released in January 2016 by Portobello Books. Han received the Premio Malaparte for the Italian translation of Human Acts, Atti Umani, by Adelphi Edizioni, in Italy on 1 October 2017. The English translation of the novel was shortlisted for the 2018 International Dublin Literary Award.
Han's third novel, The White Book, was shortlisted for the 2018 International Booker Prize. An autobiographical novel, it centers on the loss of her older sister, a baby who died two hours after her birth.
Han's novel We Do Not Part was published in 2021. It tells the story of a writer researching the 1948–49 Jeju uprising and its impact on her friend's family. The French translation of the novel won the Prix Médicis Étranger in 2023.
In 2023, Han's fourth full-length novel, Greek Lessons, was translated into English by Deborah Smith and E Yaewon. The Atlantic magazine called it a book in which "words are both insufficient and too powerful to tame".
In 2024, Han's short story "Heavy Snow" was published by the 18 November 2024 issue of The New Yorker.
In 2025, Han was among 414 South Korean writers who were signatories to a petition urging the Constitutional Court of Korea to uphold the impeachment of suspended president Yoon Suk Yeol over his martial law declaration.


== Personal life ==
Han was married to Hong Yong-hee, a literary critic and professor at Kyung Hee Cyber University. In 2024, Han stated that they had been divorced for many years. Han has a son, and they ran a bookstore in Seoul together from 2018 until November 2024, when she stepped down from its management.
Han has said that she suffers from periodic migraines and credits them with "keeping her humble".


== Awards and recognition ==
Han won the Yi Sang Literary Award (2005) for Mongolian Mark (the second part of The Vegetarian), the 25th Korean Novel Award for her novella Baby Buddha in 1999, the 2000 Today's Young Artist Award from the Korean Ministry of Culture, and the 2010 Dongri Literary Award for The Wind is Blowing.
In 2018, Han became the fifth writer chosen to contribute to the Future Library project. Katie Paterson, the project's organizer, said that Han had been chosen because she "expands our view of the world". Han delivered the manuscript, Dear Son, My Beloved, in May 2019. In the handover ceremony, she dragged a white cloth through the forest and wrapped it around the manuscript. She explained this as a reference to Korean culture, in which a white cloth is used both for babies and for mourning gowns, describing the event as "like a wedding of my manuscript with this forest. Or a lullaby for a century-long sleep".
Han was elected a Royal Society of Literature International Writer in 2023, recognizing her significant contributions to global literature and the impact of her works beyond South Korea.
The Vegetarian placed 49th in The New York Times's "100 Best Books of the 21st century" in July 2024.


=== Nobel Prize in Literature ===

In 2024, Han was awarded the Nobel Prize in Literature by the Swedish Academy for her "intense poetic prose that confronts historical traumas and exposes the fragility of human life". This made her the first Korean writer and the first female Asian writer to be awarded the Nobel Prize in Literature. The awarding was widely celebrated in South Korea, while international reactions were mixed. Han herself said she was surprised but honoured by the recognition. Han delivered her Nobel lecture, titled Light and Thread, on 7 December 2024 at the Swedish Academy in Stockholm.


=== Awards ===
1999 – Korean Novel Award for Baby Buddha
2000 – Korean Ministry of Culture Today's Young Artist Award – Literature Section
2005 – Yi Sang Literary Award for Mongolian Mark
2010 – Dongri Literary Award for The Wind is Blowing
2014 – Manhae Literary Award for Human Acts
2015 – Hwang Sun-won Literary Award for While One Snowflake Melts
2016 – Yonsei Award for Excellence in Liberal Arts
2016 – International Booker Prize for The Vegetarian
2017 – Malaparte Prize for Human Acts
2018 – Kim Yu-jeong Literary Award for Farewell
2018 – San Clemente Literary Prize for The Vegetarian
2019 – Inchon Award Media & Culture Section
2019 – Future Library project Writer of the Year
2022 – Daesan Literary Award for We Do Not Part
2022 – Kim Man-jung Literary Award for We Do Not Part
2023 – Prix Médicis étranger  for We Do Not Part
2024 – Émile Guimet Prize for Asian Literature for We Do Not Part
2024 – Ho-Am Prize in the Arts
2024 – Nobel Prize in Literature
2024 – Pony Chung Innovation Award
2026 – National Book Critics Circle Award for fiction


== Works ==


=== Novels ===
 여수의 사랑 [Love in Yeosu] (in Korean). Moonji. 1995. ISBN 9788932007502.
 검은 사슴 [Black Deer] (in Korean). Munhakdongne. 1998. ISBN 9788982811333.
 내 여자의 열매 [My Woman's Fruits] (in Korean). Changbi. 2000. ISBN 9788936436575.
 그대의 차가운 손 [Your Cold Hands] (in Korean). Moonji. 2002. ISBN 9788932013046.
 채식주의자 [The Vegetarian] (in Korean). Changbi. 2007. ISBN 9788936433598.
 바람이 분다, 가라 [The Wind Blows, Go] (in Korean). Moonji. 2010. ISBN 9788932020006.
 희랍어 시간 [Greek Lessons] (in Korean). Munhakdongne. 2011. ISBN 9788954616515.
 노랑무늬영원 [Fire Salamander] (in Korean). Moonji. 2012. ISBN 9788932023533.
 소년이 온다 [A Boy Comes = Human Acts] (in Korean). Changbi. 2014. ISBN 9788936434120.
 흰 [White = The White Book] (in Korean). Nanda. 2016. ISBN 9788954640718.
 작별하지 않는다 [We Do Not Part] (in Korean). Munhakdongne. 2021. ISBN 9788954682152.


==== In translation ====
The Vegetarian. Translated by Deborah Smith. London: Portobello Books. 2015. ISBN 9781846275623. UK
Greek Lessons. Translated by Deborah Smith and Emily Yae Won. London/New York: Hogarth. 2023. ISBN 9780593595275. UK  US
Human Acts. Translated by Deborah Smith. London: Portobello Books. 2016. ISBN 9781846275968. UK
The White Book. Translated by Deborah Smith. London: Portobello Books. 2017. ISBN 9781846276958. UK
We Do Not Part. Translated by Emily Yae Won and Paige Aniyah Morris. London/New York: Hogarth. 2025. ISBN 9780593595459. UK  US


=== Short story collections ===
내 이름은 태양꽃 ("My name is Sunflower"), Munhakdongne, 2002, ISBN 9788982814792.
붉은 꽃 이야기 ("The red flower story"), Yolimwon, 2003, ISBN 9788970633336.
천둥 꼬마 선녀 번개 꼬마 선녀 ("Thunder little fairy, lightning little fairy"), Munhakdongne, 2007, ISBN 9788954602792.
눈물상자 ("Tear box"), Munhakdongne, 2008, ISBN 9788954605816.


=== Stories ===


=== Poetry collections ===
서랍에 저녁을 넣어 두었다 ("I put dinner in the drawer"), Moonji, 2013, ISBN 9788932024639.


=== Essays ===
사랑과, 사랑을 둘러싼 것들 ("Love and things surrounding love"), Yolimwon, 2003, ISBN 9788970633695.
가만가만 부르는 노래 ("A song to sing calmly"), Bichae, 2007, ISBN 9788992036276.
Light and Thread by Moonji Publishing Co., 2025


== Adaptations ==
Baby Buddha and The Vegetarian have been made into films. Lim Woo-Seong wrote and directed Vegetarian, which was released in 2009. It was one of only 14 selections (out of 1,022 submissions) included in the World Narrative Competition of the North American Film Fest, and was noticed at the Busan International Film Festival.
Lim also adapted Baby Buddha into a screenplay, in collaboration with Han, and directed the film version. Titled Scars, it was released in 2011.


== See also ==
Korean literature
List of Korean novelists
List of Korean-language poets
List of Korean women writers
List of Nobel laureates in Literature


== References ==


== External links ==

Official website
Han Kang on Nobelprize.org
Kang, Han (28 April 2023). "Han Kang: 'One year I couldn't bear fiction and read astrophysics instead'". The Guardian. Retrieved 23 June 2023.
Zhou, Dennis (30 January 2023). "Han Kang on How Language Misses Its Mark". The New Yorker. Retrieved 23 June 2023.

In [4]:
dic = {
    "b": 1,
    "a": 2
}

list(dic.keys())[0]

'b'

In [5]:
path = '..\\data\\laureates_after_2000.csv'

import pandas as pd

df = pd.read_csv(path)
df

    Unnamed: 0  year                                               link
0          103  2000         https://en.wikipedia.org/wiki/Gao_Xingjian
1          104  2001        https://en.wikipedia.org/wiki/V._S._Naipaul
2          105  2002         https://en.wikipedia.org/wiki/Imre_Kertész
3          106  2003        https://en.wikipedia.org/wiki/J._M._Coetzee
4          107  2004     https://en.wikipedia.org/wiki/Elfriede_Jelinek
5          108  2005        https://en.wikipedia.org/wiki/Harold_Pinter
6          109  2006          https://en.wikipedia.org/wiki/Orhan_Pamuk
7          110  2007        https://en.wikipedia.org/wiki/Doris_Lessing
8          111  2008   https://en.wikipedia.org/wiki/J._M._G._Le_Clézio
9          112  2009         https://en.wikipedia.org/wiki/Herta_Müller
10         113  2010   https://en.wikipedia.org/wiki/Mario_Vargas_Llosa
11         114  2011    https://en.wikipedia.org/wiki/Tomas_Tranströmer
12         115  2012               https://en.wikipedia.org/wiki/Mo_Yan
13         116  2013          https://en.wikipedia.org/wiki/Alice_Munro
14         117  2014      https://en.wikipedia.org/wiki/Patrick_Modiano
15         118  2015  https://en.wikipedia.org/wiki/Svetlana_Alexievich
16         119  2016            https://en.wikipedia.org/wiki/Bob_Dylan
17         120  2017       https://en.wikipedia.org/wiki/Kazuo_Ishiguro
18         121  2018       https://en.wikipedia.org/wiki/Olga_Tokarczuk
19         122  2019         https://en.wikipedia.org/wiki/Peter_Handke
20         123  2020         https://en.wikipedia.org/wiki/Louise_Glück
21         124  2021    https://en.wikipedia.org/wiki/Abdulrazak_Gurnah
22         125  2022         https://en.wikipedia.org/wiki/Annie_Ernaux
23         126  2023            https://en.wikipedia.org/wiki/Jon_Fosse
24         127  2024             https://en.wikipedia.org/wiki/Han_Kang
25         128  2025  https://en.wikipedia.org/wiki/László_Krasznaho...